-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text,
  full_name text,
  avatar_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  role text DEFAULT 'founder'::text,
  phone text,
  country text,
  kyc_completed boolean DEFAULT false,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.startup_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  startup_name text NOT NULL,
  industry text CHECK (industry = ANY (ARRAY['healthcare'::text, 'fintech'::text, 'food'::text, 'ecommerce'::text])),
  stage text,
  description text,
  team_size integer,
  founded_year integer,
  website text,
  is_complete boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  contact_email text,
  contact_phone numeric,
  funding_ask numeric,
  funding_use text,
  headquarters text,
  incorporation_country text,
  legal_entity_name text,
  revenue_current_year numeric,
  monthly_burn numeric,
  runway_months integer,
  CONSTRAINT startup_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT startup_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.analysis_results (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  executive_summary text,
  slide_insights jsonb,
  red_flags jsonb,
  key_metrics jsonb,
  overall_score integer,
  created_at timestamp with time zone DEFAULT now(),
  startup_name text,
  financial_health_score integer CHECK (financial_health_score >= 0 AND financial_health_score <= 100),
  growth_potential_score integer CHECK (growth_potential_score >= 0 AND growth_potential_score <= 100),
  risk_assessment_score integer CHECK (risk_assessment_score >= 0 AND risk_assessment_score <= 100),
  current_revenue numeric DEFAULT 0,
  monthly_burn numeric DEFAULT 0,
  runway_months integer DEFAULT 0,
  team_size integer DEFAULT 0,
  funding_ask numeric DEFAULT 0,
  funding_probability_score integer CHECK (funding_probability_score >= 0 AND funding_probability_score <= 100),
  business_overview jsonb,
  funding_details jsonb,
  investment_recommendation text,
  comparable_companies jsonb,
  market_analysis jsonb,
  status text DEFAULT 'completed'::text CHECK (status = ANY (ARRAY['processing'::text, 'completed'::text, 'failed'::text])),
  CONSTRAINT analysis_results_pkey PRIMARY KEY (id),
  CONSTRAINT analysis_results_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.healthcare_details (
  startup_profile_id uuid NOT NULL,
  regulatory_approvals text,
  clinical_stage text,
  target_patient_population text,
  reimbursement_strategy text,
  clinical_partners text,
  estimated_time_to_market_months integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT healthcare_details_pkey PRIMARY KEY (startup_profile_id),
  CONSTRAINT healthcare_details_fkey FOREIGN KEY (startup_profile_id) REFERENCES public.startup_profiles(id)
);
CREATE TABLE public.fintech_details (
  startup_profile_id uuid NOT NULL,
  licencing_requirements text,
  payments_volume_30d numeric,
  kyc_process text,
  principal_markets text,
  integrations text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fintech_details_pkey PRIMARY KEY (startup_profile_id),
  CONSTRAINT fintech_details_fkey FOREIGN KEY (startup_profile_id) REFERENCES public.startup_profiles(id)
);
CREATE TABLE public.food_details (
  startup_profile_id uuid NOT NULL,
  suppliers text,
  supply_chain_risks text,
  perishability_days integer,
  food_safety_certifications text,
  gross_margin_percent numeric,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT food_details_pkey PRIMARY KEY (startup_profile_id),
  CONSTRAINT food_details_fkey FOREIGN KEY (startup_profile_id) REFERENCES public.startup_profiles(id)
);
CREATE TABLE public.ecommerce_details (
  startup_profile_id uuid NOT NULL,
  primary_channels text,
  average_order_value numeric,
  monthly_active_buyers integer,
  fulfillment_strategy text,
  return_rate_percent numeric,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ecommerce_details_pkey PRIMARY KEY (startup_profile_id),
  CONSTRAINT ecommerce_details_fkey FOREIGN KEY (startup_profile_id) REFERENCES public.startup_profiles(id)
);
CREATE TABLE public.analysis_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  startup_profile_id uuid,
  model_used text,
  request_summary text,
  response_summary text,
  created_at timestamp with time zone DEFAULT now(),
  startup_name text,
  overall_score integer CHECK (overall_score >= 0 AND overall_score <= 100),
  analysis_type text DEFAULT 'pitch_deck'::text,
  status text DEFAULT 'completed'::text CHECK (status = ANY (ARRAY['processing'::text, 'completed'::text, 'failed'::text])),
  file_name text,
  analysis_result_id uuid,
  processing_time_seconds integer,
  CONSTRAINT analysis_logs_pkey PRIMARY KEY (id),
  CONSTRAINT analysis_logs_user_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT analysis_logs_result_fkey FOREIGN KEY (analysis_result_id) REFERENCES public.analysis_results(id)
);
CREATE TABLE public.founder_assets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  personal_net_worth numeric,
  liquid_assets numeric,
  personal_annual_income numeric,
  credit_score integer CHECK (credit_score IS NULL OR credit_score >= 300 AND credit_score <= 850),
  stock_investments numeric DEFAULT 0,
  crypto_investments numeric DEFAULT 0,
  real_estate_investments numeric DEFAULT 0,
  other_investments numeric DEFAULT 0,
  total_investment_portfolio numeric DEFAULT (((COALESCE(stock_investments, (0)::numeric) + COALESCE(crypto_investments, (0)::numeric)) + COALESCE(real_estate_investments, (0)::numeric)) + COALESCE(other_investments, (0)::numeric)),
  primary_residence_value numeric,
  investment_properties_value numeric,
  total_real_estate_debt numeric,
  previous_startup_exits numeric DEFAULT 0,
  current_business_equity_value numeric,
  intellectual_property_value numeric,
  business_assets_description text,
  personal_debt numeric DEFAULT 0,
  monthly_personal_expenses numeric,
  dependents_count integer DEFAULT 0 CHECK (dependents_count >= 0),
  personal_funds_committed_to_startup numeric,
  previous_funding_raised numeric DEFAULT 0,
  investor_connections text,
  board_memberships text,
  industry_experience_years integer CHECK (industry_experience_years IS NULL OR industry_experience_years >= 0),
  previous_companies text,
  professional_network_value text,
  advisory_roles text,
  insurance_coverage_amount numeric,
  retirement_savings numeric,
  emergency_fund_months integer CHECK (emergency_fund_months IS NULL OR emergency_fund_months >= 0),
  risk_tolerance text CHECK (risk_tolerance = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT founder_assets_pkey PRIMARY KEY (id),
  CONSTRAINT founder_assets_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.news (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  content text NOT NULL,
  tag character varying NOT NULL CHECK (tag::text = ANY (ARRAY['founder'::character varying, 'investor'::character varying, 'both'::character varying]::text[])),
  timestamp timestamp with time zone NOT NULL DEFAULT now(),
  category character varying NOT NULL,
  read_time integer NOT NULL,
  summary text NOT NULL,
  CONSTRAINT news_pkey PRIMARY KEY (id)
);